version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hospital
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://admin:secret@db:5432/hospital
    depends_on:
      - db

volumes:
  postgres_data:
